### ISSUE TITLE
Full screen not hidden header

### ISSUE THREAD

**Issue by stoneWeb** [halilb/react-native-photo-browser#1]
In the Example click image hidden header and statusBar, but in my project not hidden header, why?
I use NavigatorIOS.

**Comment by halilb** [comment]
Hey @stoneWeb,

Please make sure you are passing `alwaysShowControls` props as `false`.

**Comment by stoneWeb** [comment]
set `alwaysShowControls={false}`, Still no hidden header, and the title not become “… photos ...  1 of 5”

**Comment by halilb** [comment]
I just tested the component with NavigatorIOS. It doesn't work nice with navigationBar as the component has it's own bar currently.

It works good if you pass `navigationBarHidden: true` property to your new route though. Can you try that?

**Comment by stoneWeb** [comment]
I tried, It worked. but click backbutton statusbar color not restore

**Comment by stoneWeb** [comment]
It work now, Great ✌️

**Comment by halilb** [comment]
I'm glad it worked out. Thanks for your time :)
