### ISSUE TITLE
Getting error ViewPagerAndroid has been removed from React Native

### ISSUE THREAD

**Issue by msaqlain** [halilb/react-native-photo-browser#102]
Getting error ViewPagerAndroid has been removed from React Native. It can now be installed and imported from 'react-native-viewpager' instead.

![image](https://user-images.githubusercontent.com/56955855/72326424-02b98980-36d1-11ea-9e21-db1e621e63a7.png)

**Comment by halilb** [comment]
Thanks for reporting @msaqlain. This was fixed on the master but was not published.

I just published `0.6.0` version on npm. This error should be gone when you update the library.
