### ISSUE TITLE
make backTitle and backImage configurable

### ISSUE THREAD

**Issue by mokabyls** [halilb/react-native-photo-browser#108]
Hi,

first of all, thanks for this great library ! To improve it, can you make configurable backTitle and backImage ?
Actually, we cannot override it. And maybe backImage can become a ReactNode to allowing us to pass an Icon from react-native-vector-icon for example ?

Thanks !

**Comment by halilb** [comment]
Hi @mokabyls, thanks for the issue!

I'm afraid I don't have much free time nowadays. But I'd love to review the PR if you can create one for this.

**Comment by mokabyls** [comment]
Hi @halilb, just submitted #109.

**Comment by halilb** [comment]
Closing because #109 was merged.
