### ISSUE TITLE
Images not displaying, only image-error

### ISSUE THREAD

**Issue by sun2rise** [halilb/react-native-photo-browser#16]
Hi, i am using RN 0.32
I am trying to load images hosted on a simple apache server.
I am not using httpS so i am using NSAllowsArbitraryLoads key in my info.plist file for IOS project,
so if i use a standard RN <Image..> component with an image from my server it works with no problem.
When i load PhotoBrowser component, instead, it shows me a grid full of image-error@2x.png: your error image that is a big 'X'.
This happens in the grid and of course when i try to load an image.
ReactART was installed according to your documentation.

How can I understand what's the problem? i have no message about what's wrong

Thank you!

**Comment by sun2rise** [comment]
The problem was that I was providing wrong uri path like
http://<serverIp>/Image/imgs\pic1.jpg
clearly the slashes are not ok!

Sorry i struggled over this for quite a lot and found the solution just after have opened an issue! :)

**Comment by halilb** [comment]
I'm glad you figured it out @sun2rise.
