### ISSUE TITLE
Feature Request: Add renderTopBar property

### ISSUE THREAD

**Issue by miclaus** [halilb/react-native-photo-browser#17]
First of all, thank you for this component! It's great!

We're currently implementing it for a project and it comes in handy, considering all the ready-to-go features. We do however have a special requirements:

➳ We use an own custom Header / TopBar and thus the possibility to not render the TopBar would be needed.

I'll do a quick PR ^^

**Comment by halilb** [comment]
This is implemented with #30.

**Comment by miclaus** [comment]
@halilb great !

like i said, i'm not sure it's the same :)
