### ISSUE TITLE
Rendering issue after orientation change

### ISSUE THREAD

**Issue by sun2rise** [halilb/react-native-photo-browser#19]
Hi
to reproduce this issue:
- use startOnGrid: true
- open a picture from the grid
- change orientation
- return to the grid view

after this on my iPad i see a black screen and then everything goes back to normality after a touch anywhere on the screen

does anyone confirm this?
thanks

*iOS - React 0.32.0*

**Comment by wongyikfei** [comment]
similar issue here.

Open a picture > click grid view button

then I see a black screen. 

However, if I set startOnGrid to true, which make the grid view display first, it display everything normally.

I'm using React 0.28.0

**Comment by sun2rise** [comment]
i use *startOnGrid: true*
(updated the head comment)

**Comment by wongyikfei** [comment]
I disabled the animation in index.js. Everything seems working now. Maybe it is something related to the animation.

**Comment by wongyikfei** [comment]
https://github.com/facebook/react-native/issues/8607

I added removeClippedSubviews={false} to ListView in GridContainer.js and the problem has gone.

**Comment by sun2rise** [comment]
I confirm that the solution by @wongyikfei is working.
Thank you!

**Comment by sun2rise** [comment]
Pull request https://github.com/halilb/react-native-photo-browser/pull/21
