### ISSUE TITLE
Status bar colors

### ISSUE THREAD

**Issue by edvinasbartkus** [halilb/react-native-photo-browser#2]
My app is using white status bar colors. After returning to the previous screen from PhotoBrowser it animates transition from white to black. Is it possible to disable it? I tried to look at the code but seems like only `<StatusBar />` is used and no other operations are done with StatusBar. Could it be that it is a bug from react-native?

**Comment by edvinasbartkus** [comment]
Seems like the issue was with the usage of `wix/react-native-navigation`. I have resolved the issue myself. Sorry for the wrong alarm.

**Comment by halilb** [comment]
I'm glad you figured it out :)
