### ISSUE TITLE
warning: Circular indeterminate `ProgressBarAndroid`is deprecated. Use `ActivityIndicator` instead.

### ISSUE THREAD

**Issue by travnik** [halilb/react-native-photo-browser#29]
Using component on Android.  When open photo, showed warning: 
"Circular indeterminate `ProgressBarAndroid`is deprecated. Use `ActivityIndicator` instead. "
What decide problem?

**Comment by travnik** [comment]
Also there is still a warning:
" You are manually calling a React.PropTypes validation function for the `indeterminate` prop on `ProgressBarAndroid`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details."

**Comment by akira-hiroki** [comment]
I have those issues, too. Could you please let me know how to fix these issues?

**Comment by jonolock91** [comment]
+1

**Comment by jonolock91** [comment]
Have created a pull request - https://github.com/halilb/react-native-photo-browser/pull/38/commits/c4a99fb5c787fb4362ad6034d91231ebbc3d5204

**Comment by halilb** [comment]
Thanks for reporting @travnik ! I just merged @jonolock91 's PR.
