### ISSUE TITLE
Empty space on the right side of the grid

### ISSUE THREAD

**Issue by eljago** [halilb/react-native-photo-browser#3]
Hello, awesome library, I'm really looking forward to see how it evolves.

Found a little issue: the grid doesn't fill the screen when running on the iPhone 6 Simulator

![simulator screen shot may 5 2016 11 14 26 pm](https://cloud.githubusercontent.com/assets/2080977/15062540/3594e7d2-1317-11e6-84b2-35c8d41f07de.png)

**Comment by halilb** [comment]
Thanks for your contribution @eljago. It should be fixed now.
