### ISSUE TITLE
How not to display back button?

### ISSUE THREAD

**Issue by sun2rise** [halilb/react-native-photo-browser#33]
How can i set the visibility option of the upper left back button?
Thanks

**Comment by grahamtallen** [comment]
I also would like to be able to do this

**Comment by halilb** [comment]
Hi @sun2rise, thanks for the issue!

I've just released 0.3.1 to fix this issue. Back button will not be displayed if `onBack` prop is undefined.

**Comment by sun2rise** [comment]
thanks @halilb !
