### ISSUE TITLE
native top bar (carrier info etc)

### ISSUE THREAD

**Issue by fmelp** [halilb/react-native-photo-browser#42]
Hi there,
It seems as though somewhere in your code you request to hide all the native very top bar stuff where info such as carrier, battery, notifications, etc are shown. Could you please tell me where in your source code this happens so I can get rid of it? It's sending the rest of my app's aspects off.. Thank you!

Also, it throws a lot of warning in Android due to use of deprecated methods, specifically propTypes

**Comment by halilb** [comment]
Hi @fmelp!

We don't have any StatusBar code in the library but you can try hiding/displaying it using react-native's `StatusBar` component. Checkout the documentation: https://facebook.github.io/react-native/docs/statusbar.html

**Comment by Misioka** [comment]
@halilb 
I'm issuing same problem and in FullscreenContainer at line 286 you are hiding/showing `StatusBar`
Im going to push pull request when it can be disabled by props.

Are you ok with that solution?

**Comment by halilb** [comment]
I'm sorry @fmelp, we have StatusBar code in the library indeed. I've missed that on my last comment.

@Misioka I can merge that if you can create a PR. We already have `alwaysShowControls`, but that also includes toolbar and back button.

**Comment by halilb** [comment]
This should be fixed with #48.

You can use `alwaysDisplayStatusBar={true}` to achieve this.
