### ISSUE TITLE
The grid view / images briefly display when closing the view (only on ios)

### ISSUE THREAD

**Issue by ajonno** [halilb/react-native-photo-browser#45]
hi, i found a weird issue just now right when i thought i was all done :-(   anyway, easiest way to explain it is to show you a video of the situation. Do have any thoughts on why this would be ? 

I can tell you that I put the PhotoBrowser inside a modal view, like this:
```
<Modal style={{flex: 1}}>
    <PhotoBrowser
          style={{flex: 1}}
          onBack={this.closeFullScreenImageView}
          mediaList={media}
          initialIndex={0}
          displayNavArrows={true}
          displaySelectionButtons={true}
          useCircleProgress
          onSelectionChanged={this.deleteImage}
    />
</Modal>

```
I also installed the ART library, no issues there.

Any thoughts on how to resolve or at least for now a workaround ? We need to push an update to beta testers tomorrow so hopefully can work something out soon.

![2017-05-10_19-41-24](https://cloud.githubusercontent.com/assets/3005269/25893053/c15cfc58-35b9-11e7-9dad-66a32626ab5e.gif)

UPDATE: i think i know why it's occurring. the gridview is actually sitting underneath the single screen / full screen image view. in the "onBack" function i am just closing the modal view right there and then. this i gather means that the grid view also needs to be dismissed and so we see that for a brief moment. any ideas on a better way that i could implement the desired behavior (which is just tap the back button, and completely exit / close the modal and PhotoBrowser)

**Comment by ajonno** [comment]
ah so simple.  enableGrid={false}  doh!

**Comment by halilb** [comment]
I'm glad you've got it working @ajonno :)

**Comment by painforever** [comment]
I think that's not teh way of solving the problem, can you please give people a solution when people really need the grid ? thanks
