### ISSUE TITLE
landscape orientation not supported in ios

### ISSUE THREAD

**Issue by mamdouh-mowesolutions** [halilb/react-native-photo-browser#47]
Hi,
is there a way to support landscape orientation in ios, this is work in Android,  but not in ios.
thank you.

**Comment by mamdouh-mowesolutions** [comment]
Any help, please!

**Comment by halilb** [comment]
Hi @mamdouh-mowesolutions,

It is actually supported on both platforms. You can try and see it in the example project.

What's not working with landscape orientation for you? Please re-open the issue when you provide more details.
