### ISSUE TITLE
Infinitely loading for large images?

### ISSUE THREAD

**Issue by 7kfpun** [halilb/react-native-photo-browser#5]
Hi @halilb ,

Maybe need to deal with reloading the image?

<img width="564" alt="screen shot 2016-06-02 at 7 29 37 pm" src="https://cloud.githubusercontent.com/assets/2672802/15743511/9c3beb74-28f8-11e6-9abd-96f86276b75c.png">

**Comment by halilb** [comment]
Hi @7kfpun,

I think i didn't understand the problem exactly. Do you mean that large images cannot be downloaded ever? Can you provide a sample image url if that's public?
