### ISSUE TITLE
onPhotoLongPress event does not provide the selected media

### ISSUE THREAD

**Issue by spacegraym3** [halilb/react-native-photo-browser#58]
Steps to reproduce:

1. Bring up a photo grid
2. Select a photo to view the single photo
3. Long press on the image

Expected to get the selected media object.  However, it on passes in a Proxy.  The following is the context of the passed in parameter to onPhotoLongPress.  

Any ideas?

Chris

Proxy {dispatchConfig: Object, _targetInst: Constructor, _dispatchListeners: null, isDefaultPrevented: function, isPropagationStopped: function…}[[Handler]]: Object[[Target]]: ResponderSyntheticEvent[[IsRevoked]]: false

**Comment by halilb** [comment]
Thanks for reporting @spacegraym3!

I just checked the codee and I guess you're right. Do you have some time to create a PR for this? Editing this line to make it pass media object to the parent component should be enough: https://github.com/halilb/react-native-photo-browser/blob/master/lib/FullScreenContainer.js#L228

I could also make the change and test it when I get some free time.

**Comment by spacegraym3** [comment]
Yes, I realized after submitting this that I made the change.  I'll create
a pull request in the next few days.

Thanks!

**Comment by halilb** [comment]
I just merged #63 and this should be supported in version `0.4.0`.

Thans again @spacegraym3!
