### ISSUE TITLE
iPhone X nav bar support

### ISSUE THREAD

**Issue by jonolock91** [halilb/react-native-photo-browser#70]
Would it be possible to add support for iPhone X so that the number of photos and back button have more padding top?

The way I could see this being achievable and flexible enough to update later on is to allow a style props to be passed to the TopBar.js file, then we can use a library such as https://github.com/ptelad/react-native-iphone-x-helper to detect if we're on iPhone X or not to pass the relevant styles.

**Comment by dklt** [comment]
1/2 year no effort, is this library abandoned ?

**Comment by halilb** [comment]
Fixed with #98
