### ISSUE TITLE
Grid and initialIndex not working on iOS but working on android

### ISSUE THREAD

**Issue by systemlevel** [halilb/react-native-photo-browser#75]
Experiencing an issue with iOS PhotoBrowser where the initialIndex does not load the correct photo and the grid does not go to the correct photo when tapped.

I get this most of the time when I click on a photo in the grid or try to load an initial photo through the initialIndex prop.

<img width="559" alt="screen shot 2017-12-04 at 5 29 06 pm" src="https://user-images.githubusercontent.com/894983/33583728-eb2c0986-d918-11e7-8ba1-6a8f72257e8c.png">

I'm calling the PhotoBrowser component as shown in the examples:

```
      <PhotoBrowser
        onBack={() => goBack()}
        mediaList={media}
        initialIndex={initIndex}
        displaySelectionButtons={false}
        displayActionButton={showActionButtons}
        displayTopBar={true}
        startOnGrid={false}
        enableGrid={true}
        onActionButton={this.onActionButton}
        alwaysDisplayStatusBar={true}
        customTitle={(index, rowCount) => `${index} sur ${rowCount}`}
      />
```

Again, Android works like a charm.  Not sure what's throwing off the iOS version?

Anyone experience this issue?

**Comment by linianyang** [comment]
And I've got the same problem

**Comment by ngandhy** [comment]
@systemlevel @linianyang - checkout my PR at #76

If you have an Android app can you test it there and lmk if you see any issues?
