### ISSUE TITLE
Doesn't work with latest react

### ISSUE THREAD

**Issue by sammosampson** [halilb/react-native-photo-browser#9]
If I create a new RN proect (27.2) and paste in your example I get 'No component found with the name ARTSurfaceView'

**Comment by halilb** [comment]
Thanks for reporting @sammosampson.

It sounds it's related to `ReactArt` dependency. Can you check import it to your project and see if it works. You can read ReactArt part from README file: https://github.com/halilb/react-native-photo-browser#ios

I'd like to fix it once we understand the problem.

**Comment by BelinChung** [comment]
It also does not work on iOS platform (with RN0.28.0), but there is no problem on Android
`ReactART` library has been added to my Xcode project
Error Message: `JSON value '<null>' of type NSNull cannot be converted to NSString`

Source Code
``` javascript
import React, { 
    Component     
} from 'react'

import {
    StyleSheet,
    View
} from 'react-native'

import PhotoBrowser from 'react-native-photo-browser'

const EXAMPLES = [{
    photo: 'http://ww4.sinaimg.cn/mw690/005M2osngw1f5j341r1eyj30an0andgb.jpg',
    caption: 'Grotto of the Madonna'
}]
export default class FeedbackView extends Component{
    constructor(props) {
        super(props)
        this.state = {

        }
    }

    render() {
        return (
            <View style={styles.container}>  
                <PhotoBrowser
                    onBack={this.props.navigator.pop}
                    mediaList={EXAMPLES}
                    enableGrid={false}
                    useCircleProgress={true}
                />
            </View> 
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1
    }
})
```

**Comment by BelinChung** [comment]
This seems to be RN's bug, it work correctly in last version(RN0.29.0)

**Comment by halilb** [comment]
@BelinChung sorry for my late answer. I could just check this and it's working with latest react-native version as you said.
