### ISSUE TITLE
ViewPagerAndroid RN 

### ISSUE THREAD

**Issue by ndrishinski** [halilb/react-native-photo-browser#96]
Awesome Library! 

Ran into this issue with newer version of react-native where React Native no longer has ViewPagerAndroid as is contained on FullScreenContainer.js.

The app currently crashes.

"react": "16.9.0",
"react-native": "0.61.2",
"react-native-photo-browser": "^0.5.0",

**Comment by makedirectory** [comment]
https://github.com/halilb/react-native-photo-browser/pull/99

**Comment by halilb** [comment]
Just merged #100 into master to  fix this. Could you fetch the library from master and confirm it works now @ndrishinski?

**Comment by ndrishinski** [comment]
@halilb Sorry for the delayed response. That fixed my issue! Thank you so much and thanks for making an awesome open source library !!

**Comment by halilb** [comment]
> @halilb Sorry for the delayed response. That fixed my issue! Thank you so much and thanks for making an awesome open source library !!

Great! Thanks for the feedback @ndrishinski.
